apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  labels:
    app: api-cursos-academicos
type: Opaque
stringData:
  # Cadena de conexión (texto plano - Kubernetes lo codifica automáticamente)
  ConnectionStrings__DefaultConnection: "Server=SQL1001.site4now.net;Database=db_ac177a_gestionacademica;User Id=db_ac177a_gestionacademica_admin;Password=Junior.28;Encrypt=True;TrustServerCertificate=True;MultipleActiveResultSets=True;"
  
  # JWT Settings
  JwtSettings__SecretKey: "GestionAcademica_SuperSecretKey_2025_MinLength32Characters!"
  JwtSettings__Issuer: "GestionAcademicaAPI"
  JwtSettings__Audience: "GestionAcademicaClients"
  JwtSettings__ExpirationHours: "24"
  JwtSettings__RefreshTokenExpirationDays: "7"
  
  # Email Settings
  EmailSettings__SmtpServer: "smtp.gmail.com"
  EmailSettings__SmtpPort: "587"
  EmailSettings__SenderEmail: "caterno99@gmail.com"
  EmailSettings__SenderName: "Academia Global"
  EmailSettings__Password: "aeodsesrortjsbez"
  EmailSettings__EnableSsl: "true"
  
  # App Settings
  AppSettings__FrontendUrl: "http://localhost:3000"